let dados = [
    {titulo : "Gato siamês",
    descricao: "Os gatos siameses são conhecidos por sua inteligência e personalidade marcante. Com seus olhos azuis vibrantes e corpo esguio, eles transmitem uma aura de elegância. Apesar de serem independentes, os siameses são extremamente apegados a seus tutores, adorando brincar e interagir. Sua voz característica e melodiosa os torna companheiros únicos e divertidos.",
    link: "https://www.google.com/search?client=opera-gx&hs=TtT&sca_esv=eac6bfefb75d31b9&sca_upv=1&sxsrf=ADLYWIKQ3vJYhkIv0Q_PCU4lFNK7stiNKg:1725830404038&q=gatos+siames&udm=2&fbs=AEQNm0AuaLfhdrtx2b9ODfK0pnmi046uB92frSWoVskpBryHTtShVNbk-60xlcGTvYzJ-DKSTGtJjS2FjB5pmTql0ubRQcrur8VCNRNtkKdC3ObBzLG5uJD927skmc0ffBzEdzkdZp52nu2ERhyWe9emryhFr4nDB2LaE8s4QuDoTp9HnSP9uS9slvCV2pg0Gd7Gfyv99fhHzFal7_fEgcGweIQgefBGxw&sa=X&ved=2ahUKEwiln7Oho7SIAxVVD7kGHV4QEsUQtKgLegQIExAB&biw=1495&bih=712&dpr=1.25"},

    {titulo : "Gato tricolor",
    descricao: "Os gatos tricolores são verdadeiras joias felinas. Com sua pelagem única, que combina branco, preto e laranja, eles são conhecidos como gatos da sorte por muitos marinheiros. Além da beleza, os tricolores possuem uma personalidade equilibrada e dócil, sendo companheiros ideais para qualquer família. São animais inteligentes e adaptáveis.",
    link: "https://www.google.com/search?client=opera-gx&hs=uoT&sca_esv=eac6bfefb75d31b9&sca_upv=1&sxsrf=ADLYWIKRPi_TATvg7OkV8Ul48b8BW5w5pA:1725830121666&q=gato+tricolor&udm=2&fbs=AEQNm0AuaLfhdrtx2b9ODfK0pnmi046uB92frSWoVskpBryHTtShVNbk-60xlcGTvYzJ-DKSTGtJjS2FjB5pmTql0ubRQcrur8VCNRNtkKdC3ObBzIMJ6zrxySBWn-QXNKVwb6szzrCGl5CH_8uqgkEZOSGo4YgTZercyaqX8tWwBItkB2LZ-67XSf9yzMVBTOiWFl6Ry53Nd9OcriJh7ZOYpYDhzlQQhQ&sa=X&ved=2ahUKEwihy-CaorSIAxVLJrkGHetyKMoQtKgLegQIERAB&biw=1495&bih=712&dpr=1.25"},

    {titulo : "Gato preto",
    descricao: "Os gatos pretos, envoltos em um halo de mistério, são símbolos de elegância e charme. Com seus pelos sedosos e olhos que parecem penetrar na alma, eles possuem uma presença marcante. Apesar das superstições, os gatos pretos são animais amorosos, independentes e extremamente inteligentes. São companheiros leais e apreciam momentos de carinho.",
    link: "https://www.google.com/search?q=gato+preto&client=opera-gx&hs=SUo&sca_esv=eac6bfefb75d31b9&sca_upv=1&udm=2&biw=1495&bih=712&sxsrf=ADLYWIKHhJVvHtoBGqO86h8urShC51fvBw%3A1725830136655&ei=-BPeZuXbJ-265OUPpLfW6A0&ved=0ahUKEwjlt_OhorSIAxVtHbkGHaSbFd0Q4dUDCBE&uact=5&oq=gato+preto&gs_lp=Egxnd3Mtd2l6LXNlcnAiCmdhdG8gcHJldG8yCxAAGIAEGLEDGIMBMgsQABiABBixAxiDATIFEAAYgAQyBBAAGAMyBRAAGIAEMgUQABiABDIFEAAYgAQyBRAAGIAEMgUQABiABDIOEAAYgAQYsQMYgwEYigVIoRZQzQVYhRNwBHgAkAEAmAGBAaAB-AiqAQQwLjEwuAEDyAEA-AEBmAIOoAKsCagCAsICEBAAGIAEGLEDGEMYgwEYigXCAgoQABiABBhDGIoFwgIHECMYJxjqAsICBBAjGCfCAg0QABiABBixAxhDGIoFwgIIEAAYgAQYsQOYAwOIBgGSBwQ0LjEwoAekPw&sclient=gws-wiz-serp"},

    {titulo : "Gato cinza",
    descricao: "Os gatos cinzas exalam sofisticação e serenidade. Com sua pelagem suave e olhos que podem variar do verde, azul e amarelo, eles são a personificação da calma e da elegância. Os cinzinhas são animais observadores e independentes, mas também apreciam momentos de carinho e atenção. São ótimos para quem busca um companheiro tranquilo e elegante.",
    link: "https://www.google.com/search?q=gato+cinza&client=opera-gx&hs=HVo&sca_esv=eac6bfefb75d31b9&sca_upv=1&udm=2&biw=1495&bih=712&sxsrf=ADLYWII4kb45kqXGLvfpeMAxomBK6rMXpw%3A1725830187075&ei=KxTeZpSmBLCK5OUP3cGPgQs&ved=0ahUKEwjU5_i5orSIAxUwBbkGHd3gI7AQ4dUDCBE&uact=5&oq=gato+cinza&gs_lp=Egxnd3Mtd2l6LXNlcnAiCmdhdG8gY2luemEyCxAAGIAEGLEDGIMBMgUQABiABDIFEAAYgAQyBRAAGIAEMgUQABiABDIFEAAYgAQyBRAAGIAEMgUQABiABDIFEAAYgAQyBRAAGIAESLQPUJgFWOkNcAJ4AJABAJgBd6ABnAWqAQMwLja4AQPIAQD4AQGYAgigArkFwgIQEAAYgAQYsQMYQxiDARiKBcICBBAAGAPCAgoQABiABBhDGIoFwgIOEAAYgAQYsQMYgwEYigXCAgQQIxgnwgIIEAAYgAQYsQOYAwCIBgGSBwMyLjagB9og&sclient=gws-wiz-serp"},

    {titulo : "Gato laranja",
    descricao: "Os gatos laranjas são conhecidos por sua personalidade extrovertida e alegre. Com sua pelagem vibrante e olhos verdes brilhantes, eles são a alma da festa em qualquer ambiente. Os laranjas são animais sociáveis, brincalhões e adoram chamar a atenção. São perfeitos para quem busca um companheiro cheio de energia.",
    link: "https://www.google.com/search?q=gato+laranja&client=opera-gx&hs=oVo&sca_esv=eac6bfefb75d31b9&sca_upv=1&udm=2&biw=1495&bih=712&sxsrf=ADLYWIJvW5h7s2l4C-mIOAzjrCVlsTkFhA%3A1725830220464&ei=TBTeZqqIHOn85OUP0cC0gQ4&ved=0ahUKEwiq3u7JorSIAxVpPrkGHVEgLeAQ4dUDCBE&uact=5&oq=gato+laranja&gs_lp=Egxnd3Mtd2l6LXNlcnAiDGdhdG8gbGFyYW5qYTILEAAYgAQYsQMYgwEyBRAAGIAEMgUQABiABDIFEAAYgAQyBRAAGIAEMgUQABiABDIFEAAYgAQyBRAAGIAEMgUQABiABDIFEAAYgARI4hZQwwNY8xNwAXgAkAEAmAGCAaABvAqqAQQxLjExuAEDyAEA-AEBmAINoAL9CsICBBAjGCfCAhAQABiABBixAxhDGIMBGIoFwgIKEAAYgAQYQxiKBcICDhAAGIAEGLEDGIMBGIoFwgIIEAAYgAQYsQOYAwCIBgGSBwQxLjEyoAexRA&sclient=gws-wiz-serp"},

    {titulo : "Gato branco",
    descricao: "Os gatos brancos, com seus olhos azuis intensos, transmitem uma sensação de pureza e inocência. Sua pelagem macia e brilhante os torna verdadeiros anjos de quatro patas. Apesar de sua aparência delicada, os brancos são animais fortes e independentes, que apreciam a companhia humana. São companheiros leais e amorosos.",
    link: "https://www.google.com/search?q=gato+branco&client=opera-gx&hs=eWo&sca_esv=eac6bfefb75d31b9&sca_upv=1&udm=2&biw=1495&bih=712&sxsrf=ADLYWIJnNgqBC7jdAFDXNBzPbM1CqHfO5A%3A1725830272279&ei=gBTeZoHhEP2v5OUPreOyuAg&ved=0ahUKEwiBocniorSIAxX9F7kGHa2xDIcQ4dUDCBE&uact=5&oq=gato+branco&gs_lp=Egxnd3Mtd2l6LXNlcnAiC2dhdG8gYnJhbmNvMgUQABiABDIFEAAYgAQyBRAAGIAEMgUQABiABDIFEAAYgAQyBRAAGIAEMgUQABiABDIFEAAYgAQyBRAAGIAEMgUQABiABEj6F1CkA1jOEnABeACQAQCYAXagAYwLqgEEMC4xM7gBA8gBAPgBAZgCDqACxQvCAgsQABiABBixAxiDAcICBBAjGCfCAhAQABiABBixAxhDGIMBGIoFwgIIEAAYgAQYsQPCAgoQABiABBhDGIoFwgIOEAAYgAQYsQMYgwEYigWYAwCIBgGSBwQxLjEzoAffSw&sclient=gws-wiz-serp"},
    
];
